#!/usr/bin/env bash
#'script that groups visitors by IP and HTTP status code, and displays this data The exact format must be: OCCURENCE_NUMBER IP HTTP_CODE; In list format; Ordered from the greatest to the lowest number of occurrence.'
i="apache-access.log"
awk '{print $1, $9}' $i | sort | uniq -c | sort -nr
